[project]
name = 'Real-Estate-Investment-Trust'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fractional-ownership]
path = 'contracts/fractional-ownership.clar'
clarity_version = 2
epoch = 2.5

[contracts.property-management]
path = 'contracts/property-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.property-nft]
path = 'contracts/property-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.rent-collection]
path = 'contracts/rent-collection.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
